import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang='en'
      className='container mx-auto'
    >
      <body className='container mx-auto px-4'>{children}</body>
    </html>
  );
}
